### ISSUE TITLE
Is there a BackEnd?

### ISSUE THREAD

**Issue by MrMuminov** [victorkvarghese/react-native-messenger#12]
_Hi there_
Is there a **backend** side to this program?
So the **server** part?

Or is it just the frontend part?

**Comment by MrMuminov** [comment]
> _Hi there_
> Is there a **backend** side to this program?
> So the **server** part?

**Comment by shurshilov** [comment]
yeah, where backend???

**Comment by victorkvarghese** [comment]
This is a just react native project, that mocks facebook messenger.

If you want backend please build it yourselves

**Comment by shurshilov** [comment]
Yes, this is understandable, it meant which API) there are many options)))
